---
- name: Test the connection
  ansible.builtin.ping:
- name: Setup the new version
  community.docker.docker_stack:
    name: loadbalancer
    prune: true
    compose:
      - "{{ lookup('template', 'files/docker_compose.yaml') | from_yaml }}"
    docker_cli: /usr/local/bin/docker
    with_registry_auth: true
