---
services:
  bf2:
    image: ghcr.io/community-network/bf2/bf2:latest
    restart: always
    environment:
      - DB_URL={{MONGO_DETAILS_STRING}}
    healthcheck:
      test: curl -fk http://localhost:80/ || exit 1
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

  game-info:
    image: ghcr.io/community-network/game-info/game-info:latest
    deploy:
      mode: global
      restart_policy:
        condition: any
    restart: always
    ports:
      - target: 3035
        published: 3035
        protocol: tcp
        mode: host
    healthcheck:
      test: curl --fail -s http://localhost:3035/health_check || exit 1
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

  jobse-api:
    image: ghcr.io/community-network/origin-public-api/api:latest
    restart: always
    deploy:
      mode: global
      restart_policy:
        condition: any
    environment:
      - REDIS_HOST={{REDIS_HOST}}
      - REDIS_PORT={{REDIS_PORT}}
      - REDIS_PASS={{REDIS_PASS}}
      - API_MAIN_ACCOUNT={{API_MAIN_ACCOUNT}}
      - API_MAIN_ACCOUNT_PASSWORD={{API_MAIN_ACCOUNT_PASSWORD}}
      - MONGO_DETAILS_STRING={{MONGO_DETAILS_STRING}}
      - POSTGRES_URL={{POSTGRES_URL}}
      - BFBAN_DB={{BFBAN_DB}}
      - GBAN_DB={{GBAN_DB}}
      - INFLUX_URL={{INFLUX_URL}}
      - INFLUX_USER={{INFLUX_USER}}
      - INFLUX_PASS={{INFLUX_PASS}}
      - JWT_SECRET={{JWT_SECRET}}
      - GT_GATEWAY={{GT_GATEWAY}}
    ports:
      - target: 8080
        published: 5050
        protocol: tcp
        mode: host
    healthcheck:
      test: curl --fail -s http://localhost:80/bf1/servers/?name=bob&lang=en-us || exit 1
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

  jobse-api-2:
    image: ghcr.io/community-network/origin-public-api/api:latest
    restart: always
    deploy:
      mode: global
      restart_policy:
        condition: any
    environment:
      - REDIS_HOST={{REDIS_HOST}}
      - REDIS_PORT={{REDIS_PORT}}
      - REDIS_PASS={{REDIS_PASS}}
      - API_MAIN_ACCOUNT={{API_MAIN_ACCOUNT}}
      - API_MAIN_ACCOUNT_PASSWORD={{API_MAIN_ACCOUNT_PASSWORD}}
      - MONGO_DETAILS_STRING={{MONGO_DETAILS_STRING}}
      - POSTGRES_URL={{POSTGRES_URL}}
      - BFBAN_DB={{BFBAN_DB}}
      - GBAN_DB={{GBAN_DB}}
      - INFLUX_URL={{INFLUX_URL}}
      - INFLUX_USER={{INFLUX_USER}}
      - INFLUX_PASS={{INFLUX_PASS}}
      - JWT_SECRET={{JWT_SECRET}}
      - GT_GATEWAY={{GT_GATEWAY}}
    ports:
      - target: 8080
        published: 5051
        protocol: tcp
        mode: host
    healthcheck:
      test: curl --fail -s http://localhost:80/bf1/servers/?name=bob&lang=en-us || exit 1
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

  operations-api:
    image: ghcr.io/community-network/operations-api/operations-api:latest
    restart: always
    deploy:
      mode: global
      restart_policy:
        condition: any
    ports:
      - target: 443
        published: 3034
        protocol: tcp
        mode: host
    healthcheck:
      test: curl -fk https://localhost/api/getseeder?groupid=0fda8e4c-5be3-11eb-b1da-cd4ff7dab605 || exit 1
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
