---
services:
  envoy:
    image: ghcr.io/community-network/envoy-proxy/envoy:latest
    restart: always
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    healthcheck:
      test: curl --fail -s http://localhost:8081/stats/prometheus || exit 1
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
